# Generated by Django 5.2.1 on 2025-06-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0006_alter_alk_dept_options_alter_alk_dept_group_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alk_kpi',
            name='get_1_zero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alk_kpi',
            name='is_percentage',
            field=models.BooleanField(default=False),
        ),
    ]
