# Generated by Django 5.2.1 on 2025-06-10 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0002_alk_dept_group_alk_dept_objective_alk_job_title_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alk_dept',
            options={'ordering': ['dept_name']},
        ),
        migrations.AlterModelOptions(
            name='alk_dept_group',
            options={'ordering': ['group_name']},
        ),
        migrations.AlterModelOptions(
            name='alk_dept_objective',
            options={'ordering': ['objective_name']},
        ),
        migrations.AlterModelOptions(
            name='alk_job_title',
            options={'ordering': ['job_title']},
        ),
        migrations.AlterModelOptions(
            name='alk_perspective',
            options={'ordering': ['perspective_name']},
        ),
        migrations.CreateModel(
            name='alk_employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')])),
                ('active', models.BooleanField(default=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.alk_dept')),
                ('dept_gr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.alk_dept_group')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi_app.alk_job_title')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id', 'dept', 'job_title'],
            },
        ),
    ]
