# Generated by Django 5.2.1 on 2025-06-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0010_rename_get_1_zero_alk_kpi_get_1_is_zero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alk_kpi',
            old_name='is_percentage',
            new_name='percentage_cal',
        ),
    ]
