# Generated by Django 5.2.1 on 2025-06-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0011_rename_is_percentage_alk_kpi_percentage_cal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alk_kpi',
            name='kpi_type',
            field=models.IntegerField(choices=[('1', '1 - Bigger better result = achieve/target'), ('2', '2 - Smaller better result = target/achieve'), ('3', '3 - Mistake')], max_length=20),
        ),
    ]
