# Generated by Django 5.2.1 on 2025-07-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0022_alter_alk_kpi_result_achivement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alk_kpi',
            name='percent_display',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
