# Generated by Django 5.2.1 on 2025-06-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HangHoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('unitprice', models.FloatField()),
            ],
        ),
    ]
