# Generated by Django 5.2.1 on 2025-06-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanghoa',
            name='totalamount',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='unitprice',
            field=models.IntegerField(),
        ),
    ]
