# Generated by Django 5.2.1 on 2025-06-17 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_hanghoa_totalamount_alter_hanghoa_unitprice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hanghoa',
            options={'ordering': ['Name'], 'verbose_name': 'Hàng hóa', 'verbose_name_plural': 'Hàng hóa'},
        ),
    ]
