# Generated by Django 5.2.1 on 2025-06-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0003_alter_alk_dept_options_alter_alk_dept_group_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alk_employee',
            options={'ordering': ['dept', 'user_id', 'name', 'job_title']},
        ),
        migrations.AddField(
            model_name='alk_employee',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
