# Generated by Django 5.2.1 on 2025-06-11 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0005_alter_alk_employee_options_alk_kpi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alk_dept',
            options={'ordering': ['dept_name'], 'verbose_name_plural': 'Department'},
        ),
        migrations.AlterModelOptions(
            name='alk_dept_group',
            options={'ordering': ['group_name'], 'verbose_name_plural': 'Department Group'},
        ),
        migrations.AlterModelOptions(
            name='alk_dept_objective',
            options={'ordering': ['objective_name'], 'verbose_name_plural': 'Department Objective'},
        ),
        migrations.AlterModelOptions(
            name='alk_employee',
            options={'ordering': ['dept', 'name', 'job_title'], 'verbose_name_plural': 'Employee'},
        ),
        migrations.AlterModelOptions(
            name='alk_job_title',
            options={'ordering': ['job_title'], 'verbose_name_plural': 'Job Title'},
        ),
        migrations.AlterModelOptions(
            name='alk_kpi',
            options={'ordering': ['kpi_name'], 'verbose_name_plural': 'KPI'},
        ),
        migrations.AlterModelOptions(
            name='alk_perspective',
            options={'ordering': ['perspective_name'], 'verbose_name_plural': 'Perspective'},
        ),
    ]
