# Generated by Django 5.2.1 on 2025-06-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0007_alk_kpi_get_1_zero_alk_kpi_is_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alk_kpi',
            name='kpi_type',
            field=models.CharField(choices=[('bigger_better', 'Bigger better result = achieve/target'), ('smaller_better', 'Smaller better result = target/achieve'), ('mistake', 'Mistake')], max_length=20),
        ),
    ]
