# Generated by Django 5.2.1 on 2025-06-13 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0009_alter_alk_kpi_kpi_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alk_kpi',
            old_name='get_1_zero',
            new_name='get_1_is_zero',
        ),
    ]
