# Generated by Django 5.2.1 on 2025-06-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0012_alter_alk_kpi_kpi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alk_kpi',
            name='kpi_type',
            field=models.IntegerField(choices=[('1', '1 - Bigger better result = achieve/target'), ('2', '2 - Smaller better result = target/achieve'), ('3', '3 - Mistake')], default=1),
        ),
    ]
