# Generated by Django 5.2.1 on 2025-09-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0024_alk_kpi_result_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='alk_dept',
            name='group',
            field=models.CharField(default='', max_length=100),
        ),
    ]
