# Generated by Django 5.2.1 on 2025-09-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0025_alk_dept_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alk_employee',
            name='level',
            field=models.IntegerField(choices=[(0, 'Level 0'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')]),
        ),
    ]
