# Generated by Django 5.2.1 on 2025-09-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi_app', '0026_alter_alk_employee_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alk_dept',
            name='group',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
